### ISSUE TITLE
/etc/letsencrypt does not exist after running command

### ISSUE THREAD

**Issue by jsarkisian** [edoz90/docker-gophish-latest#2]
Found another issue:

After running the fixed command from issue #1, it runs and says that the keys were created and can be found in the typical /etc/letsencrypt location. However, this location nor keys that were supposedly created does not exist after command completes.

**Comment by notdodo** [comment]
Are you searching the keys in `/etc/letsencryption` on the docker container or the host?
The command maps `/etc/letsencryption` of the container to `$(pwd)/ssl` of the host. You will find the keys inside the host folder.
