### ISSUE TITLE
Administrative Interface

### ISSUE THREAD

**Issue by rzmpzgeviii** [edoz90/docker-gophish-latest#3]
Hi, great work first of all!

_Login to administrative interface on port 3443_

Isn´t the administrative interface "https://localhost:3443" ?

![s](https://user-images.githubusercontent.com/101715188/185242674-5153156b-9f08-4c23-b131-ba574f336855.PNG)

**Comment by notdodo** [comment]
yes

**Comment by rzmpzgeviii** [comment]
I followed the steps but I can´t navigate to the localhost interface. Everything is running docker says up and running. 
What could be the reason mate?
Thanks alot! :)

**Comment by notdodo** [comment]
You need to access the admin interface from the domain (e.g. gophish.goo-gle.xyz:3443)
